### ISSUE TITLE
Display "partial shape" by stopping shaping stage after a given lookup

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/crowbar#2]
Needs implementation in harfbuzzjs/hbjs.c:do_trace

**Comment by khaledhosny** [comment]
Something similar could be achieved by drawing the buffer after each lookup (or each lookup the causes a change, if I’m understanding the current UI right), since glyph names are much harder to follow and visualize.

BTW, did you the LuaTeX OTL tracing stuff (for example start from p. 36 of http://www.pragma-ade.nl/general/manuals/fonts-mkiv.pdf), it might give you some inspirations.

**Comment by simoncozens** [comment]
The problem with drawing the buffer after each lookup is that it’s nice to get the positioning info right. You can “refuse” a lookup by returning false from the message function, so I’m going to try that approach.

**Comment by khaledhosny** [comment]
I really like this, thanks!
